/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import {
  type ProcessorRecord,
  type IProcessorHostModule,
  type ProcessorFactory,
} from "document-drive/processors/types";
import { type PHDocumentHeader } from "document-model";

// Import processor factories here as they are generated
import { renownUserProcessorFactory } from "./renown-user/factory.js";

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<
    (driveHeader: PHDocumentHeader) => Promise<ProcessorRecord[]>
  > = [];

  // Add processors here as they are generated
  factories.push(renownUserProcessorFactory(module));

  // Return the inner function that will be called for each drive
  return async (driveHeader: PHDocumentHeader): Promise<ProcessorRecord[]> => {
    const processors: ProcessorRecord[] = [];
    // Call each cached factory with the driveId
    for (const factory of factories) {
      const factoryProcessors = await factory(driveHeader);
      processors.push(...factoryProcessors);
    }

    return processors;
  };
};
