/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import {
  type ProcessorRecordLegacy,
  type IProcessorHostModuleLegacy,
  type ProcessorFactoryLegacy,
} from "document-drive";
import { type PHDocumentHeader } from "document-model";

// Import processor factories here as they are generated
import { renownUserProcessorFactory } from "./renown-user/factory.js";
import {
  renownCredentialProcessorFactory,
  type IProcessorHostModuleWithReactor,
} from "./renown-credential/factory.js";

export const processorFactory = (
  module: IProcessorHostModuleLegacy | IProcessorHostModuleWithReactor,
) => {
  // Initialize all processor factories once with the module
  const factories: Array<
    (driveHeader: PHDocumentHeader) => Promise<ProcessorRecordLegacy[]>
  > = [];

  // Add processors here as they are generated
  factories.push(renownUserProcessorFactory(module));
  factories.push(
    renownCredentialProcessorFactory(
      module as IProcessorHostModuleWithReactor,
    ),
  );

  // Return the inner function that will be called for each drive
  return async (driveHeader: PHDocumentHeader): Promise<ProcessorRecordLegacy[]> => {
    const processors: ProcessorRecordLegacy[] = [];
    // Call each cached factory with the driveId
    for (const factory of factories) {
      const factoryProcessors = await factory(driveHeader);
      processors.push(...factoryProcessors);
    }

    return processors;
  };
};
